**NANDINI BAJAJ 18CY20020**
Lab 5

In [1]:
import math
import numpy as np

In [2]:
a = 0
b = 0
c = 0
d = 0

In [3]:
def sin(x):
    return math.sin(x)
def sin2(x):
    return math.sin(2*x)
def dsin(x):
    return math.cos(x)
def sinsq(x):
    return math.sin(x)**2
def sinsq2(x):
    return math.sin(2*x)**2
def sin_1(x):
    return (math.sin(x) / math.sqrt(a))
def sin2_1(x):
    return (math.sin(2*x) / math.sqrt(c))
def dsin_2(x):
    return -1*(math.sin(x) / math.sqrt(a))
def dsin2_2(x):
    return -4*(math.sin(2*x) / math.sqrt(c))

def cos(x):
    return math.cos(x)
def dcos(x):
    return -math.sin(x)
def cos2(x):
    return math.cos(2*x)
def cossq(x):
    return math.cos(x)**2
def cossq2(x):
    return math.cos(2*x)**2
def cos_1(x):
    return (math.cos(x) / math.sqrt(b))
def cos2_1(x):
    return (math.cos(2*x) / math.sqrt(d))
def dcos_2(x):
    return -1*(math.cos(x) / math.sqrt(b))
def dcos2_2(x):
    return -4*(math.cos(2*x) / math.sqrt(d))

In [4]:
def trapezoidal(f, x0, xn, n):
    h = (xn - x0) / n
    integral = f(x0) + f(xn)
    for i in range(1,n):
        k = x0 + i * h
        integral = integral + 2 * f(k)
    
    integral = integral * h / 2
    return integral

In [5]:
def trapezoidal_multi(f1, f2, x0, xn, n):
  h = (xn - x0) / n
  integral = f1(x0) * f2(x0) + f1(xn) * f2(xn)
  for i in range(1,n):
    k = x0 + i * h
    integral = integral + 2 * f1(k) * f2(k)
  
  integral = integral * h / 2
  return integral

In [6]:
st = 0
nd = 2 * math.pi

a = trapezoidal(sinsq, st, nd, 20)
b = trapezoidal(cossq, st, nd, 10)
c = trapezoidal(sinsq2, st, nd, 20)
d = trapezoidal(cossq2, st, nd, 20)

print("<phi|phi> before normalization: " + str(a) + str(b) + str(c) + str(d) + "\n")
arr_1=[sin_1, sin2_1, cos_1, cos2_1]

for i in range(4):
  for j in range(i+1, 4):
    print("Integration on multiplying: ", arr_1[i].__name__ , arr_1[j].__name__, " is: ", round(trapezoidal_multi(arr_1[i], arr_1[j], st, nd, 20), 3))

print("\n")        
print("If all the above values are zero we can say, the basis set is orthogonal for L")
      

<phi|phi> before normalization: 
3.141592653589793 3.141592653589793 3.141592653589793 3.1415926535897936


Integration of multiplicaton of:  sin_1 sin2_1  is:  -0.0
Integration of multiplicaton of:  sin_1 cos_1  is:  0.0
Integration of multiplicaton of:  sin_1 cos2_1  is:  -0.0
Integration of multiplicaton of:  sin2_1 cos_1  is:  -0.0
Integration of multiplicaton of:  sin2_1 cos2_1  is:  0.0
Integration of multiplicaton of:  cos_1 cos2_1  is:  -0.0

All values are zero implies basis set is orthogonal for L


In [7]:
arr_2 = [dsin_2, dsin2_2, dcos_2, dcos2_2]
H = np.zeros([4,4])

for i in range(4):
  for j in range(4):
    H[i][j] = round(trapezoidal_multi(arr_1[i], arr_2[j], st, nd, 200), 3)
      
h_ = 1.0545e-34
m = 9.1e-31
const = -(h_**2) / (2*m)

print(const*H)

[[ 6.10972665e-39  0.00000000e+00 -0.00000000e+00 -0.00000000e+00]
 [ 0.00000000e+00  2.44389066e-38  0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00  0.00000000e+00  6.10972665e-39  0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00  0.00000000e+00  2.44389066e-38]]
